# Generated by Django 5.2 on 2025-09-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rawg', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rawg', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rawg', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_principal', models.URLField(blank=True, max_length=500, null=True)),
                ('imagen_adicional', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('metacritic', models.IntegerField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('generos', models.ManyToManyField(related_name='juegos', to='appJuegalo.genero')),
                ('plataformas', models.ManyToManyField(related_name='juegos', to='appJuegalo.plataforma')),
            ],
            options={
                'ordering': ['-rating', '-metacritic'],
            },
        ),
    ]
