# Generated by Django 5.2 on 2025-10-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJuegalo', '0002_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juego',
            options={'ordering': ['-rating', '-metacritic'], 'verbose_name_plural': 'Juegos'},
        ),
        migrations.AddField(
            model_name='juego',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=29990, max_digits=10),
        ),
        migrations.AddField(
            model_name='juego',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
